

export const TOOLTIP_MSG = {
    PRECO: "Preço do último fechamento da ação.",
    DY: "Indicador utilizado para relacionar os proventos pagos por uma companhia e o preço atual de suas ações.",
    PL: "Dá uma ideia do quanto o mercado está disposto a pagar pelos lucros da empresa.",
    PEG_RATIO: "O PEG Ratio é uma métrica de avaliação para determinar o trade-off relativo entre o preço de uma ação, o lucro gerado por ação e o crescimento esperado da empresa. Para o cálculo, assumimos o LPA Atual baseado nos últimos 4 trimestres, e o LPA Anterior os 4 trimestres anteriores a estes.",
    PVP: "Facilita a análise e comparação da relação do preço de negociação de um ativo com seu VPA.",
    EV_EBITDA: "O EV (Valor da Firma), indica quanto custaria para comprar todos os ativos da companhia, descontando o caixa. Este indicador mostra quanto tempo levaria para o valor calculado no EBITDA pagar o investimento feito para compra-la.",
    EV_BIT: "O EV (Valor da Firma), indica quanto custaria para comprar todos os ativos da companhia, descontando o caixa. Este indicador mostra quanto tempo levaria para o valor calculado no EBIT pagar o investimento feito para compra-la.",
    P_EBITDA: "O EBITDA permite conhecer quanto a companhia está gerando de caixa com base exclusivamente em suas atividades operacionais, desconsiderando os impactos financeiros e dos impostos.",
    P_EBIT: "Indica qual é o preço da ação em relação ao seu resultado EBIT. O EBIT pode ser considerado uma aproximação do lucro operacional da companhia.",
    VPA: "Indica qual o valor patrimonial de uma ação.",
    P_ATIVO: "Preço da ação dividido pelos Ativos totais por ação.",
    LPA: "Indica se a empresa é ou não lucrativa. Se este número estiver negativo, a empresa está com margens baixas, acumulando prejuízos.",
    PSR: "Valor de mercado da empresa dividido pela receita operacional líquida ou preço da ação dividido pela receita líquida por ação",
    P_CAP_GIRO: "Preço da ação dividido pelo capital de giro por ação. Capital de Giro é o Ativo Circulante menos Passivo Circulante.",
    P_ATIVO_CIRC: "É a diferença entre o ativo circulante e o passivo que constam do balanço patrimonial de uma empresa.",
    DIVIDA_LIQUIDA_PATRIM_LIQ: "Indica quanto de dívida uma empresa está usando para financiar os seus ativos em relação ao patrimônio dos acionistas.",
    DIVIDA_LIQUIDA_EBITDA: "Indica quanto tempo seria necessário para pagar a dívida líquida da empresa considerando o EBITDA atual. Indica também o grau de endividamento da companhia.",
    DIVIDA_LIQUIDA_EBIT: "Indica quanto tempo seria necessário para pagar a dívida líquida da empresa considerando o EBIT atual. Indica também o grau de endividamento da companhia.",
    PATRIMONIO_ATIVO: "O Patrimônio de uma empresa é o resultado da subtração dos ativos com os passivos. Este indicador é para mostrar a relação dos ativos no patrimônio da empresa.",
    PASSIVOS_ATIVOS: "Calculo para saber a relação entre os ativos (circulantes e não circulantes) e os passivos de uma empresa.",
    LIQ_CORRENTE: "Indica a capacidade de pagamento da empresa no curto prazo.",
    MARGEM_BRUTA: "Mede, objetivamente, o quanto a empresa ganha com a venda de seus produtos.",
    MARGEM_EBITDA: "É o percentual da divisão entre o EBITDA e a receita líquida de uma companhia. Muito útil para se comparar a lucratividade operacional da empresa.",
    MARGEM_EBIT: "Útil para comparar a lucratividade operacional de empresas do mesmo segmento, além de contribuir para avaliar o crescimento da eficiência produtiva de um negócio ao longo do tempo.",
    ROE: "Mede a capacidade de agregar valor de uma empresa a partir de seus próprios recursos e do dinheiro de investidores.",
    ROA: "O retorno sobre os ativos ou Return on Assets, é um indicador de rentabilidade, que calcula a capacidade de uma empresa gerar lucro a partir dos seus ativos, além de indiretamente, indicar a eficiência dos seus gestores.",
    ROIC: "Mede a rentabilidade de dinheiro o que uma empresa é capaz de gerar em razão de todo o capital investido, incluindo os aportes por meio de dívidas.",
    GIRO_ATIVO: "Mede se como uma empresa está utilizando o seu ativo (bens, investimentos, estoque etc.) para produzir riqueza, através da venda de seus produtos e/ou serviços.",
    CAGR_RECEITA_5A: "O CAGR (Compound Annual Growth Rate), ou taxa de crescimento anual composta, é a taxa de retorno necessária para um investimento crescer de seu saldo inicial para o seu saldo final.",
    CAGR_LUCRO_5A: "O CAGR (Compound Annual Growth Rate), ou taxa de crescimento anual composta, é a taxa de retorno necessária para um investimento crescer de seu saldo inicial para o seu saldo final.",
    MARGEM_LIQ_EBIT: "Revela a porcentagem de lucro em relação às receitas de uma empresa.",
    PATRIM_LIQ: "Patrimônio é a soma de todos os ativos de uma entidade. Patrimônio Líquido é a diferença entre os ativos e passivos."
}