@startuml DiagramaContexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(personAlias, "Usuário", "Acessa o sistema")
System(applicacao, "InfoInvestBr", "É um sistema gerenciador de renda variável")
System_Ext(autoricaoGoogle, "Google", "Responsável pela autenticação de usuário ao sistema.")
System_Ext(yahooFinance, "Yahoo Finance", "Responsável é Yahoo Finance  pela disponibilização dos dados de cotações.")
Person(admin, "Administrador" , "Responsável por gerenciar e atualizar os dados do sistema como proventos e novos ativos")


Rel(personAlias, applicacao, "Acessa", "Visualiza os ativos e sua carteira de investimento")
Rel(applicacao,autoricaoGoogle, "Verificar", "Verifica se usuário possui uma conta no Google")
Rel(applicacao,yahooFinance, "Busca", "Busca cotação em tempo real")
Rel(admin, applicacao, "Gerencia", "Gerencia dados")
@endumls